### ISSUE TITLE
Where is MIDINoteSequence?

### ISSUE THREAD

**Issue by vietdragon2009** [allthemusicllc/libatm#4]
$ if [ -f $CARGO  ] && [ -x $CARGO ]
> then
>     echo "::: INFO: Checking code for errors" && \
>     cargo check --lib && \
>     echo "::: INFO: Building code in release mode" && \
>     cargo build --release && \
>     echo "::: INFO: Running library and doc tests" && \
>     cargo test --lib && cargo test --doc
> else
>     echo "::: ERROR: Failed to locate cargo executable"
>     exit 1
> fi
::: INFO: Checking code for errors
    Checking atm v0.2.0 (/home/li)
error[E0433]: failed to resolve: could not find `MIDINoteSequence` in `libatm`
   --> src/directives.rs:214:27
    |
214 |         let seq = libatm::MIDINoteSequence::new(
    |                           ^^^^^^^^^^^^^^^^ could not find `MIDINoteSequence` in `libatm`

error[E0412]: cannot find type `MIDINoteSequence` in crate `libatm`
  --> src/directives.rs:13:75
   |
13 | fn parse_sequence_argument<'a>(matches: &clap::ArgMatches<'a>) -> libatm::MIDINoteSequence {
   |                                                                           ^^^^^^^^^^^^^^^^ not found in `libatm`

error[E0412]: cannot find type `MIDINoteSequence` in crate `libatm`
  --> src/directives.rs:15:45
   |
15 |     let sequence = sequence.parse::<libatm::MIDINoteSequence>().unwrap();
   |                                             ^^^^^^^^^^^^^^^^ not found in `libatm`

error[E0412]: cannot find type `MIDINoteSequence` in crate `libatm`
  --> src/directives.rs:87:27
   |
87 |     pub sequence: libatm::MIDINoteSequence,
   |                           ^^^^^^^^^^^^^^^^ not found in `libatm`

error[E0412]: cannot find type `MIDINoteSequence` in crate `libatm`
   --> src/directives.rs:128:27
    |
128 |     pub sequence: libatm::MIDINoteSequence,
    |                           ^^^^^^^^^^^^^^^^ not found in `libatm`

error[E0412]: cannot find type `MIDINoteSequence` in crate `libatm`
   --> src/directives.rs:241:27
    |
241 |     pub sequence: libatm::MIDINoteSequence,
    |                           ^^^^^^^^^^^^^^^^ not found in `libatm`

error[E0599]: no method named `gen_buffer` found for type `libatm::MIDIFile` in the current scope
   --> src/utils.rs:367:19
    |
367 |             mfile.gen_buffer().unwrap().as_slice(),
    |                   ^^^^^^^^^^ method not found in `libatm::MIDIFile`

error: aborting due to 7 previous errors

Some errors have detailed explanations: E0412, E0433, E0599.
For more information about an error, try `rustc --explain E0412`.
error: could not compile `atm`.

To learn more, run the command again with --verbose.

**Comment by eplouf** [comment]
To build that, I had to revert 181b2f927b535908793dce5c1639965370b7c2c4 , which works with atm-cli pointing to d4a3250af5f503f32650903f15ab3f17c4c6d523
